name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: fissible/.github/.github/workflows/test-bash.yml@main
    with:
      bootstrap-command: python3 -m pip install pytest pyte --break-system-packages
